//
// Copyright (c) 2017, 2021 ADLINK Technology Inc.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ADLINK zenoh team, <zenoh@adlink-labs.tech>
//

use async_std::sync::Arc;
use async_trait::async_trait;
use std::collections::HashMap;
use zenoh_flow::{
    default_output_rule, types::ZFResult, zf_data, zf_empty_state, ZFComponent,
    ZFComponentOutputRule, ZFContext, ZFDataTrait, ZFPortID, ZFSourceTrait,
};
use zenoh_flow_examples::ZFUsize;

static SOURCE: &str = "Random";

#[derive(Debug)]
struct ExampleRandomSource;

impl ZFComponent for ExampleRandomSource {
    fn initialize(
        &self,
        _configuration: &Option<HashMap<String, String>>,
    ) -> Box<dyn zenoh_flow::ZFStateTrait> {
        zf_empty_state!()
    }
}

impl ZFComponentOutputRule for ExampleRandomSource {
    fn output_rule(
        &self,
        _context: &mut ZFContext,
        state: &mut Box<dyn zenoh_flow::ZFStateTrait>,
        outputs: &HashMap<String, Arc<dyn zenoh_flow::ZFDataTrait>>,
    ) -> ZFResult<HashMap<ZFPortID, zenoh_flow::ZFComponentOutput>> {
        default_output_rule(state, outputs)
    }
}

#[async_trait]
impl ZFSourceTrait for ExampleRandomSource {
    async fn run(
        &self,
        _context: &mut ZFContext,
        _state: &mut Box<dyn zenoh_flow::ZFStateTrait>,
    ) -> ZFResult<HashMap<ZFPortID, Arc<dyn ZFDataTrait>>> {
        let mut results: HashMap<ZFPortID, Arc<dyn ZFDataTrait>> = HashMap::with_capacity(1);
        results.insert(
            String::from(SOURCE),
            zf_data!(ZFUsize(rand::random::<usize>())),
        );
        async_std::task::sleep(std::time::Duration::from_secs(1)).await;
        Ok(results)
    }
}

// Also generated by macro
zenoh_flow::export_source!(register);

fn register() -> ZFResult<Box<dyn ZFSourceTrait + Send>> {
    Ok(Box::new(ExampleRandomSource) as Box<dyn ZFSourceTrait + Send>)
}
