[package]
#rust-version = { workspace = true }
name = "zenoh-flow-examples"
repository.workspace = true
version.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
#description = "Internal crate for zenoh-flow."
#readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
# async-std = "1.12"
# async-trait = "0.1"
# prost = "0.11"
# zenoh-flow = { version = "=0.5.0-alpha.1" }

# zenoh-flow = { workspace = true }
# async-trait = { workspace = true }
# async-std = { workspace = true }
# prost = { workspace = true }

#[workspace.dependencies]
# async-std = "1.12"
# async-trait = "0.1"
# prost = "0.11"
# zenoh-flow = { version = "0.5.0-alpha.1" }

[dev-dependencies]
async-std = "1.12"
async-trait = "0.1"
prost = "0.11"
zenoh-flow = { version = "=0.5.0-alpha.2" }

[build-dependencies]
rustc_version = "0.4.0"

[[example]]
name = "greetings-maker"
path = "examples/greetings-maker/src/lib.rs"
crate-type = ["cdylib"]

[[example]]
name = "file-writer"
path = "examples/file-writer/src/lib.rs"
crate-type = ["cdylib"]

[[example]]
name = "period-miss-detector"
path = "examples/period-miss-detector/src/lib.rs"
crate-type = ["cdylib"]
