//
// Copyright (c) 2017, 2021 ADLINK Technology Inc.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ADLINK zenoh team, <zenoh@adlink-labs.tech>
//

use std::io;
use rand::Rng;
use zenoh_flow::{
    serde::{Deserialize, Serialize},
    operator::{SinkTrait, FnSinkRun, RunResult, DataTrait, StateTrait, FnInputRule, InputRuleResult},
    types::{ZFLinkId, ZFContext, Token},
};
use std::collections::HashMap;
use async_std::sync::Arc;
use std::any::Any;



#[derive(Serialize, Deserialize, Debug)]
struct ExampleGenericSink {}


//derived by a #[derive(ZFState)] macro
impl StateTrait for ExampleGenericSink {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn as_mut_any(&mut self) -> &mut dyn Any {
        self
    }
}

impl ExampleGenericSink {

    pub fn ir_1(
        _ctx: &mut ZFContext,
        _inputs: &mut HashMap<ZFLinkId, Token>,
    ) -> InputRuleResult {
        Ok(true)
    }


    pub fn run_1(_ctx: &mut ZFContext, inputs: HashMap<ZFLinkId, Arc<dyn DataTrait>>) -> () {
        println!("#######");
        for (k, v) in inputs {
            print!("Example Generic Sink Received on LinkId {:?} -> {:?}", k, v);
        }
        println!("#######");
    }
}





impl SinkTrait for ExampleGenericSink {

    fn get_input_rule(&self, ctx: &ZFContext) -> Box<FnInputRule> {
        match ctx.mode {
            0 => Box::new(Self::ir_1),
            _ => panic!("No way"),
        }
    }

    fn get_run(&self, ctx: &ZFContext) -> Box<FnSinkRun> {
        match ctx.mode {
            0 => Box::new(Self::run_1),
            _ => panic!("No way"),
        }
    }

    fn get_state(&self) -> Box<dyn StateTrait> {
        unimplemented!()
    }

    fn serialize_state(&self) -> Vec<u8> {
        unimplemented!()
    }

    // fn deserialize_state() -> Arc<dyn StateTrait> {
    //     unimplemented!()
    // }
}

// //Also generated by macro
zenoh_flow::export_sink!(register);

extern "C" fn register(registrar: &mut dyn zenoh_flow::loader::ZFSinkRegistrarTrait) {
    registrar.register_zfsink(
        "print",
        Box::new(ExampleGenericSink{}) as Box<dyn zenoh_flow::operator::SinkTrait + Send>,
    );
}